FE-3-2team/team2taskify

- package-lock.json
- package.json
- src/components/common/Badge.tsx
- src/components/common/Profile.tsx
- src/hooks/useWindow.tsx
- src/pages/test.tsx
- src/types/global.d.ts
* create Badge , Badges
* badge.length 가 4 이하일때는 +n 뱃지가 안보이게 예외 처리
* badge.length 가 0 일때 예외 처리
* window resize 이벤트로 device갑 반환하는 hook 추가 
* npm i 하세요
* lodash.throttle 추가 했습니다. 
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Feat] create Badge, profile

- package-lock.json
- package.json
- src/components/common/Badge.tsx
- src/components/common/Comments.tsx
- src/pages/test.tsx
- src/types/global.d.ts
* edit comment
npm i 하세요
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Refacor]Comment

- src/api/dashboard.ts
- src/components/ModalContents/EditDashboard.tsx
- src/components/common/Chip/Color.chip.tsx
* create Edit dashboard
*
*
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Feat] Edit dashboard

- src/api/column.api.ts
- src/components/ModalContents/InputModal.tsx
- src/components/common/ModalPopup.tsx
- src/types/global.d.ts
* 인풋 하나달린 모달 컨텐츠 만들었습니다.
* 비밀번호가 일치하지 않습니다 등 alert 역할을 하는 모달 컨텐츠도 children으로 넘겨서 사용해주시면 됩니다.
* 컬럼 생성시 중복된 이름을 테스트하는 인풋 모달에는 isColumn 을 prop으로 전달해 주세요!
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Feat] create inputModal

- src/api/dashboard.ts
- src/components/ModalContents/NewDashboard.tsx
- src/components/common/Button/Button.tsx
- src/components/common/Chip/Color.chip.tsx
- src/components/common/Header.tsx
- src/components/common/InvitedDashboards/InvitedDashboards.tsx
- src/components/common/InvitedDashboards/Search.InvDash.tsx
- src/components/common/ModalPopup.tsx
- src/pages/mydashboard.tsx
* create Mydashboard page
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Feat] Mydashboard page

- src/api/member.ts
- src/components/EditMember.tsx
- src/pages/dashboard/[dashboardId]/edit.tsx
* Editpage 의 EditMember 페이지 네이션
* Editpage 의 EditMember 삭제 시, 경우에 따라 페이지 네이션 할수 있게 로직 작성 
*
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Feat]Editpage 의 EditMember 페이지 네이션, 삭제 핸들링

- src/api/card.api.ts
- src/api/column.api.ts
- src/components/common/Column.tsx
- src/components/common/Dropdown/DropdownAssigneeSearch.tsx
- src/components/common/ImageUploadBox.tsx
- src/components/common/TagInputField.tsx
- src/hooks/useCreateCard.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
- src/utils/date.ts
#90 
* 할일카드 생성 모달 구현 완료
* 에러 해결
* 중복 및 미사용 코드 정리
* 코드 일부 별개파일로 분리
추후에 리팩토링 한 번 더 하겠습니다.
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Feat] Complete new card modal and fix errors

- src/assets/icons/CheckBox.svg
- src/assets/icons/UnCheckBox.svg
- src/components/EditProfile.tsx
- src/components/Login/LoginForm.tsx
- src/components/Login/SingupForm.tsx
- src/components/common/Input.tsx
- src/pages/login.tsx
- src/pages/signup.tsx
* 체크박스 이미지 적용
* 전체 페이지 색, 링크텍스트 색상 적용
* 재현님 리뷰 부분 반영
* input disable optional 적용
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Style] 로그인,회원가입 페이지 디자인 수정

- src/components/AssigneeCard.tsx
- src/components/Comments.tsx
- src/components/ModalContents/Card.modal.tsx
- src/components/common/ModalPopup.tsx
- src/pages/mydashboard.tsx
* 카드 상세보기 모달 반응형
* 수정하기 버튼 클릭시, 카드 수정 모달 팝업 기능 추가 예정
*
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Style] 카드 상세보기 모달 반응형

- src/components/EditProfile.tsx
- src/components/common/Header.tsx
- src/components/common/Input.tsx
- src/components/common/Loding.tsx
- src/components/common/Skeleton.tsx
- src/components/common/Skeleton/Skeleton.tsx
- src/components/common/Skeleton/SkeletonChangePasswordForm.tsx
- src/components/common/Skeleton/SkeletonEditProfile.tsx
- src/components/common/Skeleton/SkeletonSideMenu.tsx
- src/components/common/Skeleton/WithSkeleton.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
- src/pages/mypage.tsx
- src/styles/globals.css
* mypage 스켈레톤 및 로딩스피너 생성
* editprofile.tsx 추가 및 스타일 수정
* 헤더 놓친 스타일 수정
- EditProfile.tsx 전달사항 : npm i 
- editprofile.tsx 닉네임 필수값 삭제 및 수정전 border컬러 수정 부탁드려용
> [Refactor] #99 mypage 작업완료 및 스켈레톤 생성

- src/components/EditProfile.tsx
- src/components/common/Input.tsx
* 현선님 피드백 반영
*
*
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Fix] * 숨김처리, 이메일 인풋 스타일 수정

- src/api/instance.ts
- src/pages/mydashboard.tsx
- src/utils/AuthContext.tsx
- src/utils/localstorage.ts
* 3월 28일 금요일 배포
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Develop] 3월 28일 금요일 배포

- src/api/instance.ts
- src/pages/mydashboard.tsx
- src/utils/AuthContext.tsx
- src/utils/localstorage.ts
Reverts FE-3-2team/team2taskify#110
>  Reverts FE-3-2team/team2taskify#110

- next.config.ts
- src/api/auth.ts
- src/api/instance.ts
- src/components/ChangePasswordForm.tsx
* 비밀번호컴포넌트 auth.ts 사용해서 소스 간소화
* api > instance.ts 에러객체 전달하는 소스로 수정
- 프로필컴포넌트 이미지 next/image 사용해서 구현해주세용
- 프로필 저장하기 클릭시 모달이 뜬다던지의 어떠한 액션이 있어야할거가태용
> [Fix] #99 mypage 오류 수정

- src/components/EditProfile.tsx
- src/components/Login/LoginForm.tsx
- src/components/Login/SingupForm.tsx
* 로그인,회원가입 버튼 호버 스타일 삭제
* 이미지 기본값 외에 X버튼 구현
* 닉네임 없을때 에러 처리
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Feat] 프로필 컨테이너 수정

- src/api/column.api.ts
- src/api/dashboard.ts
- src/api/member.ts
- src/components/EditDashboard.tsx
- src/components/EditMember.tsx
- src/components/EditProfile.tsx
- src/components/InvitationHistory.tsx
- src/components/ModalContents/EditCardModal.tsx
- src/components/ModalContents/InputModal.tsx
- src/components/common/Header.tsx
- src/components/common/ModalPopup.tsx
- src/hooks/useEditCardSubmit.tsx
- src/hooks/useFetchColumns.tsx
- src/hooks/useFormatDate.tsx
- src/pages/dashboard/[dashboardId]/edit.tsx
- src/pages/mydashboard.tsx
- src/types/global.d.ts
* editpage
* header 수정
* 타입 에러 수정 string -> Date 
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Refactoring]  에러 모달 팝업, header 수정 

- package-lock.json
- package.json
- src/components/FadeInWhenVisible.tsx
- src/components/TrailParticles.tsx
- src/components/common/SideMenu.tsx
- src/pages/index.tsx
- src/styles/globals.css
* 사이드메뉴 스타일 삭제된부분 재추가(모바일 10개 표출 및 페이지네이션 hidden 처리)
* 인덱스페이지 모션 추가
* 마우스 이펙트 추가
npm i 해주셔요
> [Refactor] 사이드메뉴 스타일 재수정 & 인덱스 모션 추가

- src/components/EditProfile.tsx
- src/components/Login/SingupForm.tsx
- src/components/ModalContents/AlertModal.tsx
*
*
*
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Fix] 모달 타임아웃처리, 기본 이미지 저장 오류 처리

- src/api/card.api.ts
- src/components/ModalContents/CreateCard.modal.tsx
- src/components/ModalContents/EditCard.modal.tsx
- src/components/common/Card/CardValues.tsx
- src/components/common/Column.tsx
- src/components/common/Dropdown/DropdownAssigneeSearch.tsx
- src/components/common/Dropdown/DropdownProgress.tsx
- src/components/common/ImageUploadBox.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
* 수정시 assignee , 컬럼 변경 오류 수정 
* 상세페이지 overflow-x laptop으로 브레이크 포인트 이동
*
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Refactor] 수정시 assignee , 컬럼 변경 오류 수정 

- src/api/card.api.ts
- src/components/ModalContents/Card.modal.tsx
- src/components/ModalContents/EditCard.modal.tsx
- src/components/common/Card/CardValues.tsx
- src/components/common/Chip/Status.chip.tsx
- src/components/common/Column.tsx
- src/components/common/ModalPopup.tsx
- src/components/common/SortableCard.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
* 카드 수정후 화면에 반영 
* 카드 수정 모달 오류 수정 (수정하기 버튼 클릭시 너무 많은 모달이 뜸)
* 드래그앤 드랍 요소 드랍후에 리렌더링 
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [fix] 카드 수정후 화면에 반영 ,카드 수정 모달 오류 수정

- src/components/common/ModalPopup.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
*
*
*
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Style] [dashboardId] 페이지에서 스타일  오류 수정

- src/pages/dashboard/[dashboardId]/index.tsx
* 헤더 스타일 오류 해결 
*
*
* 라벨을 적용했나요?
* 담당자 선택했나요?
> [Style] 헤더 스타일 오류 해결 
